### ISSUE TITLE
Do not upload `node_modules` Folder and Implement Proper `.gitignore` Practices

### ISSUE THREAD

**Issue by ragibalasad** [muhammadshihab/tailwind-01#1]
Hey Rashu, I noticed that the `node_modules` folder got added to the repository. It's a common mistake! Here's why you should avoid doing this:

### What happened:
The `node_modules` folder, which holds all the project dependencies, got pushed to the repo. 
This directory can get huge, which makes the repo unnecessarily large and slow to clone. 

It’s not necessary to include `node_modules` in version control since it can be easily installed locally with `npm install` or `yarn install`, making it redundant as everyone can recreate it using the `package.json` and `package-lock.json` files.

### How to avoid this in the future: 
- You should add a `.gitignore` file (if there isn’t one already) and make sure it includes `node_modules/` so Git won’t track it.
- To fix it now, you’ll need to run `git rm -r --cached node_modules` to remove it from the repo, and then commit and push those changes.

Once that’s sorted, you’ll be good to go! Let me know if you need a hand with anything.

**Comment by rushdv** [comment]
okey,
 let me try

**Comment by rushdv** [comment]
vai pacchi na ,
r ekhon notun kore korte chailam ta ekhon fir commit e hocche na

**Comment by ragibalasad** [comment]
github template theke .gitignore file ta add kor. ar node_modules folder tao github theke delete kor. tarpor local repository te pull kore ne

**Comment by rushdv** [comment]
kam ho geya,
jazakallahu khairan bhai
